# This is a basic workflow to help you get started with Actions

name: LaTeX Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: readme2tex-action
        uses: montali/readme2tex-action@1.1.1
